// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebAPI.Data;

namespace WebAPI.Migrations
{
    [DbContext(typeof(CVContext))]
    [Migration("20180821073516_updateToPersonModel")]
    partial class updateToPersonModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("addressLine1")
                        .HasColumnName("Address Line 1");

                    b.Property<string>("addressLine2")
                        .HasColumnName("Address Line 2");

                    b.Property<string>("addressLine3")
                        .HasColumnName("Address Line 3");

                    b.Property<int>("cell")
                        .HasColumnName("Cell");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnName("DOB");

                    b.Property<string>("email")
                        .HasColumnName("Email");

                    b.Property<string>("firstName")
                        .HasColumnName("First Name");

                    b.Property<string>("gender")
                        .HasColumnName("Gender");

                    b.Property<int>("idNumber")
                        .HasColumnName("ID Number");

                    b.Property<string>("lastName")
                        .HasColumnName("Last Name");

                    b.Property<string>("maidenName")
                        .HasColumnName("Maiden Name");

                    b.Property<int?>("tel")
                        .HasColumnName("Tel");

                    b.HasKey("id");

                    b.ToTable("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
